routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});
Auth::routes();

//Route::group(['prefix'=>LaravelLocalization::setLocale()],function(){

    Route::group(['namespace'=>'Website','as'=>'website.'],function (){
        Route::get('/', 'IndexController@index');
        Route::resource('/courses', 'CoursesController');

        Route::get('/register_courses', 'CoursesController@registerAll');
        Route::get('/ajax_category/{id}', 'CoursesController@ajaxCategory');
        Route::get('/ajax_course/{id}', 'CoursesController@ajaxCourse');
        Route::get('/ajax_course_datails/{id}', 'CoursesController@ajaxCourseDetails');
        Route::get('/course_single/{id}', 'CoursesController@courseSingle');
        Route::get('/course_details/{id}', 'CoursesController@coursedetails');
        Route::get('/register_single_course/{id}', 'CoursesController@registerSingle');
        Route::get('/all_in_category/{id}', 'CoursesController@allinCategory');
        Route::get('/all_courses/', 'CoursesController@allCourses');
        Route::get('/available_courses/', 'CoursesController@availableCourses');
        Route::get('/about_us/', 'CoursesController@aboutUs');
        Route::get('/privacy/', 'CoursesController@privacy');
        Route::get('/cancellation/', 'CoursesController@cancellation');
        Route::get('/terms/', 'CoursesController@terms');
        Route::get('/services/{id}', 'CoursesController@showService');
        Route::get('/our_partner/', 'CoursesController@ourPartner');
        Route::get('/methodology/', 'CoursesController@Methodology');
        Route::get('/all_clients/', 'CoursesController@allClients');
        Route::get('/corporate/', 'CoursesController@corporate');
        Route::get('/company/', 'CoursesController@publicc');
        Route::get('/elearning/', 'CoursesController@elearning');
        Route::get('/weekend/', 'CoursesController@weekend');
        Route::resource('/contact', 'ContactUsController');
        Route::resource('/callback', 'CallBackController');
        Route::get('/categories', 'IndexController@categories');
        Route::get('/showmainservices/', 'CoursesController@showMainService');
        Route::get('/subservices/{id}', 'CoursesController@showSubService');

        Route::get('/pay', 'CartController@pay');
        Route::get('/shopping-cart', 'CartController@shoppingCart');
        Route::get('/invoice-details', 'CartController@invoice');
        Route::resource('/carts', 'CartController');
        Route::get('add/cart/{id}','CartController@addItem');
        Route::get('minus/cart/{id}','CartController@minusItem');
        Route::get('delete/cart/{id}','CartController@deleteItem')->name('delete.cart.update');

        Route::get('/confirmation', 'CartController@confirmation');

        Route::get('/training_methodology', 'CoursesController@trainingMethodology');
        Route::get('/blogs', 'CoursesController@showBlogs');
        Route::get('/blog_single/c', 'CoursesController@showSingleBlog');
        Route::get('/search_blogs', 'CoursesController@searchBlogs');

        Route::patch('/settings', 'SettingController@update')->name('settings.update');

    });

//});

//admin
Route::group(array('prefix' => 'dashboard','as'=>'admin.', 'middleware' => 'admin'), function() {
    Route::get('/', 'Admin\IndexController@index');

    //GEO

    Route::resource('course', 'Admin\CourseController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('slider', 'Admin\SliderController');
    Route::resource('city', 'Admin\CityController');
    Route::resource('date', 'Admin\DateController');
    Route::resource('requestcourse', 'Admin\RequestCourseController');
    Route::resource('callmeback', 'Admin\CallMeBackController');
    Route::resource('contactus', 'Admin\ContactUsController');
    Route::resource('slider', 'Admin\SliderController');
    Route::resource('user', 'Admin\UserController');
    Route::resource('clients', 'Admin\ClientController');
    Route::resource('partners', 'Admin\PartnerController');
    Route::resource('services', 'Admin\ServicesController');
    Route::resource('blogs', 'Admin\BlogController');
    Route::resource('instructors', 'Admin\InstructorController');
    Route::resource('mainservices', 'Admin\MainServiceController');
    Route::resource('credits', 'Admin\CreditController');

    Route::resource('coursecities', 'Admin\CourseCitiesController');
    Route::get('coursecities/{id}/all', 'Admin\CourseCitiesController@all');
    Route::get('coursecities/create/{id}', 'Admin\CourseCitiesController@createcity');

    Route::get('course/{id}/approve', 'Admin\CourseController@approve');
    Route::get('course/{id}/un-approve', 'Admin\CourseController@unApprove');

});

app/Models/Credit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Credit extends Model
{

    protected $table = 'credits';
    public $timestamps = true;
    protected $fillable = array('name_en', 'body_en','name_ar','body_ar','image');


}

app/Http/Controllers/Admin/CreditController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Credit;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Image;

class CreditController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $credits=Instructor::all();
        return view('admin.credits.index',compact('credits'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.credits.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'image'=>'required',
            'name_ar'=>'required',
            'name_en'=>'required'
        ]);
        $credits = Credit::create($request->all());

        if ($request->hasFile('image'))
        {
            $img = $request->file('image');
            $destinationPath = base_path() . '/images';
            $extension = $img->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $img->move($destinationPath, $name); // uploading file to given
            $credits->update(['image' => 'images/' . $name]);
        }
        return back()->withFlashMessage('credit added successfully ');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $credits =Credit::findOrFail($id);
        return view('admin.credits.edit',compact('credits'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id, Request $request)
    {

        $credits = Credit::findOrFail($id);

        $credits->update($request->all());
        if ($request->hasFile('image'))
        {
            $img = $request->file('image');
            $destinationPath = base_path() . '/images';
            $extension = $img->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $img->move($destinationPath, $name); // uploading file to given
            $credits->update(['image' => 'images/' . $name]);
        }
        return back()->withFlashMessage('credit updated successfully ');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $q = Credit::findOrFail($id);
        $q->delete();
        $data = [
            'status' => 1,
            'msg' => 'credit deleted successfully',
            'id' => $id
        ];
        return response()->json($data, 200);


    }

}

?>

resources/views/admin/credits/add.blade.php
@extends('admin.layout')
@section('title') add new credit
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->

    <div class="box">
        <div class="box-header">
            Add new credit
        </div>
        <div class="box-content">
            {!! Form::open([
               'route' => 'admin.credits.store',
               'method' => 'POST',
               'class' => 'form-horizontal',
               'files' => true
             ]) !!}
            @include('admin.credits.form')
            {!!Form::close() !!}

        </div>
    </div>

@endsection

resources/views/admin/credits/edit.blade.php
@extends('admin.layout')
@section('title') edit credit
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->

    <div class="box">
        <div class="box-header">
            Edit credit data
        </div>
        <div class="box-content">
            {!! Form::model($instructor,
                          ['route'=>['admin.credits.update',$instructor->id],
                           'method'=>'PATCH',
                           'files' => true
            ])!!}
            @include('admin.credits.form')

            {!!Form::close() !!}


        </div>
    </div>

@endsection

resources/views/admin/credits/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="row">
        <div class="col-lg-12">
            {!! Form::label('Credit Name (english)') !!}
        </div>
        <div class="col-lg-12">
            {!! Form::text('name_en',null,['class'=>'form-control']) !!}
            @if ($errors->has('name_en'))
                <span class="help-block">
                    <strong>{{ $errors->first('name_en') }}</strong>
                </span>
            @endif
        </div>
    <div class="col-lg-12">
        {!! Form::label('Credit description (english)') !!}
    </div>
    <div class="col-lg-12">
        {!! Form::textArea('body_en',null,['class'=>'form-control']) !!}
        @if ($errors->has('body_en'))
            <span class="help-block">
                    <strong>{{ $errors->first('body_en') }}</strong>
                </span>
        @endif

    </div>
        <div class="col-lg-12">
            {!! Form::label('Credit Name (arabic)') !!}
        </div>
        <div class="col-lg-12">
            {!! Form::text('name_ar',null,['class'=>'form-control']) !!}
            @if ($errors->has('name_ar'))
                <span class="help-block">
                    <strong>{{ $errors->first('name_ar') }}</strong>
                </span>
            @endif
        </div>
        <div class="col-lg-12">
            {!! Form::label('Credit description (arabic)') !!}
        </div>

        <div class="col-lg-12">
            {!! Form::textArea('body_ar',null,['class'=>'form-control']) !!}
            @if ($errors->has('body_ar'))
                <span class="help-block">
                    <strong>{{ $errors->first('body_ar') }}</strong>
                </span>
            @endif
        </div>

    <div class="col-lg-12">
        {!! Form::label('Credit Image') !!}
    </div>
    <div class="col-lg-12">
        {!! Form::file('image' , [
           "class" => "form-control file_upload_preview",
           "data-preview-file-type" => "text"
       ]) !!}
        @if ($errors->has('image'))
            <span class="help-block">
                    <strong>{{ $errors->first('image') }}</strong>
                </span>
        @endif
    </div>
    <div class="col-md-12" style="text-align: center;">
        <!-- Button trigger modal -->
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>

resources/views/admin/credits/index.blade.php
@extends('admin.layout')
@section('title')
    Instructors
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="box">
        <div class="box-header" data-original-title>
            Show all Instructors
        </div>

        <div class="box-content">
            <table id="example2" class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Credit Name </th>
                    <th>Credit image </th>
                    <th>Edit</th>
                    <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                <?php $i = 0 ?>
                @foreach($credits as $info)
                    <?php $i++ ?>
                    <tr id="removable{{$info->id}}">
                        <td>{{$i}}</td>
                        <td class="center">{{$info->name_ar}}</td>
                        <td><img class="img-responsive center-block"
                                 style="width:70px;height: 70px"
                                 src="{{url('/../'.$info->image)}}"/>
                        </td>
                        <td class="center"><a class="btn btn-success"
                                              href="{{URL::route('admin.credits.edit',$info->id)}}">
                                <i class="fa fa-edit "></i>
                            </a>
                        </td>

                        <td class="center">
                            <button id="{{$info->id}}" data-token="{{ csrf_token() }}"
                                    data-route="{{URL::route('admin.credits.destroy',$info->id)}}"
                                    type="button" class="destroy btn btn-danger "><i class="fa fa-trash-o "></i>
                            </button>
                            </a>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection