routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});
Auth::routes();

//Route::group(['prefix'=>LaravelLocalization::setLocale()],function(){

    Route::group(['namespace'=>'Website','as'=>'website.'],function (){
        Route::get('/', 'IndexController@index');
        Route::resource('/courses', 'CoursesController');

        Route::get('/register_courses', 'CoursesController@registerAll');
        Route::get('/ajax_category/{id}', 'CoursesController@ajaxCategory');
        Route::get('/ajax_course/{id}', 'CoursesController@ajaxCourse');
        Route::get('/ajax_course_datails/{id}', 'CoursesController@ajaxCourseDetails');
        Route::get('/course_single/{id}', 'CoursesController@courseSingle');
        Route::get('/course_details/{id}', 'CoursesController@coursedetails');
        Route::get('/register_single_course/{id}', 'CoursesController@registerSingle');
        Route::get('/all_in_category/{id}', 'CoursesController@allinCategory');
        Route::get('/all_courses/', 'CoursesController@allCourses');
        Route::get('/available_courses/', 'CoursesController@availableCourses');
        Route::get('/about_us/', 'CoursesController@aboutUs');
        Route::get('/privacy/', 'CoursesController@privacy');
        Route::get('/cancellation/', 'CoursesController@cancellation');
        Route::get('/terms/', 'CoursesController@terms');
        Route::get('/services/{id}', 'CoursesController@showService');
        Route::get('/our_partner/', 'CoursesController@ourPartner');
        Route::get('/methodology/', 'CoursesController@Methodology');
        Route::get('/all_clients/', 'CoursesController@allClients');
        Route::get('/corporate/', 'CoursesController@corporate');
        Route::get('/company/', 'CoursesController@publicc');
        Route::get('/elearning/', 'CoursesController@elearning');
        Route::get('/weekend/', 'CoursesController@weekend');
        Route::resource('/contact', 'ContactUsController');
        Route::resource('/callback', 'CallBackController');
        Route::get('/categories', 'IndexController@categories');
        Route::get('/showmainservices/', 'CoursesController@showMainService');
        Route::get('/subservices/{id}', 'CoursesController@showSubService');

        Route::get('/pay', 'CartController@pay');
        Route::get('/shopping-cart', 'CartController@shoppingCart');
        Route::get('/invoice-details', 'CartController@invoice');
        Route::resource('/carts', 'CartController');
        Route::get('add/cart/{id}','CartController@addItem');
        Route::get('minus/cart/{id}','CartController@minusItem');
        Route::get('delete/cart/{id}','CartController@deleteItem')->name('delete.cart.update');

        Route::get('/confirmation', 'CartController@confirmation');

        Route::get('/training_methodology', 'CoursesController@trainingMethodology');
        Route::get('/blogs', 'CoursesController@showBlogs');
        Route::get('/blog_single/c', 'CoursesController@showSingleBlog');
        Route::get('/search_blogs', 'CoursesController@searchBlogs');

        Route::patch('/settings', 'SettingController@update')->name('settings.update');

    });

//});

//admin
Route::group(array('prefix' => 'dashboard','as'=>'admin.', 'middleware' => 'admin'), function() {
    Route::get('/', 'Admin\IndexController@index');

    //GEO

    Route::resource('course', 'Admin\CourseController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('slider', 'Admin\SliderController');
    Route::resource('city', 'Admin\CityController');
    Route::resource('date', 'Admin\DateController');
    Route::resource('requestcourse', 'Admin\RequestCourseController');
    Route::resource('callmeback', 'Admin\CallMeBackController');
    Route::resource('contactus', 'Admin\ContactUsController');
    Route::resource('slider', 'Admin\SliderController');
    Route::resource('user', 'Admin\UserController');
    Route::resource('clients', 'Admin\ClientController');
    Route::resource('partners', 'Admin\PartnerController');
    Route::resource('services', 'Admin\ServicesController');
    Route::resource('blogs', 'Admin\BlogController');
    Route::resource('instructors', 'Admin\InstructorController');
    Route::resource('mainservices', 'Admin\MainServiceController');
    Route::resource('credits', 'Admin\CreditController');

    Route::resource('coursecities', 'Admin\CourseCitiesController');
    Route::get('coursecities/{id}/all', 'Admin\CourseCitiesController@all');
    Route::get('coursecities/create/{id}', 'Admin\CourseCitiesController@createcity');

    Route::get('course/{id}/approve', 'Admin\CourseController@approve');
    Route::get('course/{id}/un-approve', 'Admin\CourseController@unApprove');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $table = 'categories';
    public $timestamps = true;
    protected $fillable = array('name_ar','name', 'image');

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\Course;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Image;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $categories=Category::all();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.categories.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|string|',
            'image'=>'required'
        ]);
     $category = Category::create($request->all());

      if ($request->hasFile('image'))
      {
            $img = $request->file('image');
            $destinationPath = base_path() . '/images';
            $extension = $img->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $img->move($destinationPath, $name); // uploading file to given
            $category->update(['image' => 'images/' . $name]);
}
        return back()->withFlashMessage('Category added successfuly ');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $courses=Course::where('category_id',$id)->get();
        return view('admin.categories.show',compact('courses'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $category=Category::findOrFail($id);
        return view('admin.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id, Request $request)
    {
        $this->validate($request, [
            'name' => 'required'

        ]);
        $category = Category::findOrFail($id);

        $category->update($request->all());
         if ($request->hasFile('image'))
      {
            $img = $request->file('image');
            $destinationPath = base_path() . '/images';
            $extension = $img->getClientOriginalExtension(); // getting image extension
            $name = time() . '' . rand(11111, 99999) . '.' . $extension; // renameing image
            $img->move($destinationPath, $name); // uploading file to given
            $category->update(['image' => 'images/' . $name]);
}
        return back()->withFlashMessage('Category updated successfuly ');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $q = Category::findOrFail($id);
        $q->delete();
        $data = [
            'status' => 1,
            'msg' => 'Category deleted successfully',
            'id' => $id
        ];
        return response()->json($data, 200);


    }

}

?>

resources/views/admin/categories/add.blade.php
@extends('admin.layout')
@section('title') add new category
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->

    <div class="box">
        <div class="box-header">
            Add new category
        </div>
        <div class="box-content">
            {!! Form::open([
               'route' => 'admin.category.store',
               'method' => 'POST',
               'class' => 'form-horizontal',
               'files' => true
             ]) !!}
            @include('admin.categories.form')
            {!!Form::close() !!}

        </div>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout')
@section('title') add new category
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->

    <div class="box">
        <div class="box-header">
            Add new category
        </div>
        <div class="box-content">
            {!! Form::model($category,
                          ['route'=>['admin.category.update',$category->id],
                           'method'=>'PATCH',
                           'files' => true
            ])!!}
            @include('admin.categories.form')

            {!!Form::close() !!}


        </div>
    </div>

@endsection

resources/views/admin/categories/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="row">
    <div class="form-group">
        <div class="col-lg-12">
            {!! Form::label('Category Name in (English)') !!}
        </div>
        <div class="col-lg-12">
            {!! Form::text('name',null,['class'=>'form-control']) !!}
            @if ($errors->has('name'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group">

    <div class="col-lg-12">
        {!! Form::label('Category Name in (Arabic)') !!}
    </div>
    <div class="col-lg-12">
        {!! Form::text('name_ar',null,['class'=>'form-control']) !!}
        @if ($errors->has('name_ar'))
            <span class="help-block">
                    <strong>{{ $errors->first('name_ar') }}</strong>
                </span>
        @endif
    </div>
    </div>
    <div class="form-group">

    <div class="col-lg-12">
        {!! Form::label('Category Image') !!}
    </div>
    <div class="col-lg-12">
        {!! Form::file('image' , [
           "class" => "form-control file_upload_preview",
           "data-preview-file-type" => "text"
       ]) !!}
        @if ($errors->has('image'))
            <span class="help-block">
                    <strong>{{ $errors->first('image') }}</strong>
                </span>
        @endif
    </div>
    </div>
    <div class="form-group">

    <div class="col-md-12" style="text-align: center;">
        <!-- Button trigger modal -->
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
    </div></div>

resources/views/admin/categories/index.blade.php
@extends('admin.layout')
@section('title')
    Categories
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="box">
        <div class="box-header" data-original-title>
            Show all categories
        </div>

        <div class="box-content">
            <table id="example2" class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Category Name </th>
                    <th>Category Name (arabic) </th>
                    <th>Edit</th>
                    <th>Delete</th>


                </tr>
                </thead>
                <tbody>
                <?php $i = 0 ?>
                @foreach($categories as $info)
                    <?php $i++ ?>
                    <tr id="removable{{$info->id}}">
                        <td>{{$i}}</td>
                        <td class="center"><a href="{{URL::route('admin.category.show',$info->id)}}">{{$info->name}}</a></td>
                        <td class="center"><a href="{{URL::route('admin.category.show',$info->id)}}">{{$info->name_ar}}</a></td>
                        <td class="center"><a class="btn btn-success"
                                              href="{{URL::route('admin.category.edit',$info->id)}}">
                                <i class="fa fa-edit "></i>
                            </a>
                        </td>

                        <td class="center">
                            <button id="{{$info->id}}" data-token="{{ csrf_token() }}"
                                    data-route="{{URL::route('admin.category.destroy',$info->id)}}"
                                    type="button" class="destroy btn btn-danger "><i class="fa fa-trash-o "></i>
                            </button>
                            </a>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layout')
@section('title')
    Courses
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="box">
        <div class="box-header" data-original-title>
            Show all courses in category
        </div>

        <div class="box-content">
            <table id="example2" class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Course Name </th>
                    <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                @if(isset($courses))
                <?php $i = 0 ?>
                @foreach($courses as $info)
                    <?php $i++ ?>
                    <tr id="removable{{$info->id}}">
                        <td>{{$i}}</td>
                        <td class="center">{{$info->name}}</td>

                        <td class="center">
                            <button id="{{$info->id}}" data-token="{{ csrf_token() }}"
                                    data-route="{{URL::route('admin.course.destroy',$info->id)}}"
                                    type="button" class="destroy btn btn-danger "><i class="fa fa-trash-o "></i>
                            </button>
                            </a>
                        </td>
                    </tr>
                @endforeach
@endif
                </tbody>
            </table>
        </div>
    </div>
@endsection